name: Accessibility & Performance CI

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
  lighthouse-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: web/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: web

      - name: Build application
        run: npm run build:ci
        working-directory: web
        env:
          NEXT_PUBLIC_SITE_URL: https://permit-school.com

      - name: Start server
        run: |
          nohup npm run start:ci >/dev/null 2>&1 &
          echo "Waiting for http://127.0.0.1:4040 ..."
          for i in {1..60}; do
            if curl -fsS http://127.0.0.1:4040 >/dev/null; then
              echo "✅ server ready"
              break
            fi
            sleep 1
          done
        working-directory: web
        env:
          NEXT_PUBLIC_SITE_URL: https://permit-school.com

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v11
        with:
          configPath: web/.lighthouserc.cjs
          uploadArtifacts: true
          temporaryPublicStorage: true

      - name: Run axe-core accessibility tests
        run: |
          cd web
          npm run axe:ci
        env:
          NEXT_PUBLIC_SITE_URL: https://permit-school.com

  lint-a11y:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: web/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: web

      - name: Run ESLint with accessibility rules
        run: npm run lint:a11y
        working-directory: web

      - name: Type check
        run: npm run typecheck
        working-directory: web

  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: web/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: web

      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        working-directory: web

      - name: Build application
        run: npm run build:ci
        working-directory: web
        env:
          NEXT_PUBLIC_SITE_URL: http://127.0.0.1:4040
          TESTKIT_ON: true
          TESTKIT_TOKEN: ${{ secrets.TESTKIT_TOKEN }}

      - name: Start server
        run: |
          nohup npm run start:ci >/dev/null 2>&1 &
          echo "Waiting for http://127.0.0.1:4040 ..."
          for i in {1..60}; do
            if curl -fsS http://127.0.0.1:4040 >/dev/null; then
              echo "✅ server ready"
              break
            fi
            sleep 1
          done
        working-directory: web
        env:
          NEXT_PUBLIC_SITE_URL: http://127.0.0.1:4040
          TESTKIT_ON: true
          TESTKIT_TOKEN: ${{ secrets.TESTKIT_TOKEN }}

      - name: Run E2E tests
        run: npx playwright test --reporter=line
        working-directory: web
        env:
          BASE_URL: http://127.0.0.1:4040
          TESTKIT_ON: true
          TESTKIT_TOKEN: ${{ secrets.TESTKIT_TOKEN }}

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: web/playwright-report/
          retention-days: 30

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: web/test-results/
          retention-days: 30

      - name: Upload traces
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-traces
          path: web/test-results/
          retention-days: 30
