name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify Cursor rules present
        run: |
          test -f .cursorrules -o -f cursor.rules.md || (echo "Missing .cursorrules/cursor.rules.md" && exit 1)
      - name: Prettier check (md/yaml/json)
        run: |
          FILES=$(git ls-files '**/*.md' '**/*.mdx' '**/*.yml' '**/*.yaml' '**/*.json')
          if [ -n "$FILES" ]; then
            npx --yes prettier@3.3.3 -c $FILES
          else
            echo "No files to check."
          fi
      - name: ShellCheck scripts
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
          # shellcheck all Bash scripts (ignore if none)
          find ops -type f -name "*.sh" -print0 | xargs -0 -r shellcheck -S style -x
      - name: SQLFluff (Postgres) on migrations
        run: |
          python -m pip install --upgrade pip
          pip install "sqlfluff==3.0.6"
          sqlfluff lint --dialect postgres supabase/migrations/*.sql
      - name: Web linting
        run: |
          cd web
          npm ci
          npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Smoke script
        run: bash ops/checks/smoke.sh
      - name: Budget sanity checks
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          jq -e '.kill_switch == true' ops/config/budgets.json
          jq -e '.token_budget_per_24h <= 300000' ops/config/budgets.json

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "build ok"
