name: web-ci

on:
  pull_request:
    paths:
      - "web/**"
      - ".github/workflows/web.yml"
  push:
    branches: [main]
    paths:
      - "web/**"
      - ".github/workflows/web.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Build
        env:
          # Avoid failing on missing optional env at build time
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL || 'https://example.supabase.co' }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY || 'anon-placeholder' }}
          # Build metadata
          NEXT_PUBLIC_COMMIT_SHA: ${{ github.sha }}
          NEXT_PUBLIC_BUILD_AT: ${{ github.run_started_at }}
          # Suppress Sentry warnings in CI
          SENTRY_SUPPRESS_GLOBAL_ERROR_HANDLER_FILE_WARNING: 1
        run: npm run build:ci
