name: web-ci

on:
  pull_request:
    paths:
      - "web/**"
      - ".github/workflows/web.yml"
  push:
    branches: [main]
    paths:
      - "web/**"
      - ".github/workflows/web.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: '1'
      # Map GitHub Secrets/Vars → process.env
      SUPABASE_URL: ${{ secrets.CI_SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.CI_SUPABASE_SERVICE_ROLE_KEY }}
      SUPABASE_ANON_KEY: ${{ secrets.CI_SUPABASE_ANON_KEY }}
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.CI_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.CI_SUPABASE_ANON_KEY }}
      OPENAI_API_KEY: ${{ secrets.CI_OPENAI_API_KEY }}
      STRIPE_SECRET_KEY: ${{ secrets.CI_STRIPE_SECRET_KEY }}
      NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.CI_STRIPE_PUBLISHABLE_KEY }}
      RESEND_API_KEY: ${{ secrets.CI_RESEND_API_KEY }}
      TESTKIT_ON: 'true'
      TESTKIT_TOKEN: ${{ secrets.CI_TESTKIT_TOKEN }}
      BASE_URL: 'http://localhost:4330'
      NEXT_PUBLIC_ENV: 'ci'
      NEXT_PUBLIC_SITE_URL: 'http://localhost:4330'
    defaults:
      run:
        working-directory: web

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          check-latest: true

      - name: Show node/npm
        run: |
          node -v
          npm -v

      - name: Update npm (workaround optionalDependencies install bugs)
        run: npm i -g npm@latest

      - name: Clean install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm cache clean --force
          npm install --no-audit --prefer-online

      - name: Write .env files from secrets
        run: node ../tools/env/ci-setup.mjs

      - name: Build
        run: npm run build:ci

      - name: Start web server (background)
        run: npm run start:ci &
        env:
          PORT: 4330

      - name: Wait for /en to be ready
        run: npx wait-on -t 120000 http-get://localhost:4330/en

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Unit tests
        run: npm run test -- --run

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: E2E tests
        run: npx playwright test --reporter=line --project=chromium

      - name: Lighthouse CI
        run: npx lhci autorun --config=.lighthouserc.cjs
        env:
          PORT: 4330

      - name: Accessibility tests
        run: npm run axe:ci
