name: web-ci

on:
  pull_request:
    paths:
      - "web/**"
      - ".github/workflows/web.yml"
  push:
    branches: [main]
    paths:
      - "web/**"
      - ".github/workflows/web.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          check-latest: true

      - name: Show node/npm
        run: |
          node -v
          npm -v

      - name: Update npm (workaround optionalDependencies install bugs)
        run: npm i -g npm@latest

      - name: Clean install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm cache clean --force
          npm install --no-audit --prefer-online

      - name: Dependency sanity check (rollup)
        run: |
          node -e "try{const r=require('rollup');console.log('rollup ok:', typeof r==='object');}catch(e){console.error('rollup not resolvable');process.exit(1)}"
          node -e "try{require.resolve('@rollup/rollup-linux-x64-gnu');console.log('linux-x64-gnu pkg present');}catch{console.log('linux-x64-gnu pkg NOT present (ok if not needed on this runner)');}"

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Build
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL || 'https://example.supabase.co' }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY || 'anon-placeholder' }}
          NEXT_PUBLIC_COMMIT_SHA: ${{ github.sha }}
          NEXT_PUBLIC_BUILD_AT: ${{ github.run_started_at }}
          SENTRY_SUPPRESS_GLOBAL_ERROR_HANDLER_FILE_WARNING: 1
        run: npm run build:ci
