name: web-ci

on:
  pull_request:
    paths:
      - "web/**"
      - ".github/workflows/web.yml"
  push:
    branches: [main]
    paths:
      - "web/**"
      - ".github/workflows/web.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: |
          # Remove existing node_modules and package-lock.json to avoid Rollup issues
          rm -rf node_modules package-lock.json
          
          # Install dependencies fresh with .npmrc configuration
          npm install --no-audit --no-fund
          
          # Ensure Rollup dependencies are properly installed for Linux
          npm install @rollup/rollup-linux-x64-gnu @rollup/rollup-linux-x64-musl --no-audit --no-fund
          
          # Verify Sentry is properly installed
          npm list @sentry/nextjs
          
          # If Rollup is still missing, try alternative approach
          if ! npm list @rollup/rollup-linux-x64-gnu; then
            echo "Rollup dependency missing, trying alternative installation..."
            npm install rollup --no-audit --no-fund
          fi

      - name: Lint
        run: npm run lint --if-present

      - name: Typecheck
        run: npm run typecheck --if-present

      - name: Build
        env:
          # Avoid failing on missing optional env at build time
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL || 'https://example.supabase.co' }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY || 'anon-placeholder' }}
          # Suppress Sentry warnings in CI
          SENTRY_SUPPRESS_GLOBAL_ERROR_HANDLER_FILE_WARNING: 1
        run: npm run build
